(()=>{
const t=document.getElementById('langTrigger'),m=document.getElementById('langMenu'),code=document.getElementById('langCode'),menu=document.getElementById('menuBtn'),panel=document.getElementById('mobilePanel'),modal=document.getElementById('infoModal'),mt=document.getElementById('modalTitle'),mp=document.getElementById('modalText');
let lang=localStorage.getItem('aoi-lang')||'uk';
const dict={
uk:{
'nav.home':'Головна','nav.about':'Про студію','nav.projects':'Проєкти','nav.work':'Напрями','nav.principles':'Принципи','nav.contact':'Контакти',
'hero.translation':'Місце, що поєднує серця.','hero.summary':'Ми створюємо технології, дослідження та цифрові продукти там, де людські потреби зустрічаються зі штучним інтелектом.','hero.projects':'Наші проєкти','hero.about':'Про студію',
'manifest.translation':'Від робота до людини. Від людини до робота.','manifest.p1':'Ми віримо, що технологія повинна підсилювати людину там, де цього потребують, і залишати людині простір для емпатії, творчості та глибокого розуміння.','manifest.p2':'Ми будуємо системи, які допомагають людям розуміти складний світ, приймати рішення, створювати та взаємодіяти з цифровими системами природніше.','manifest.p3':'Технології — це не мета. Це міст між людьми, і саме в цьому сенсі вони стають по-справжньому цінними.',
'work.subtitle':'Що ми створюємо','work.lead':'Наші рішення народжуються на перетині технологій, досліджень, креативності та потреб людей.','work.all':'Усі проєкти','work.ai':'ШІ-системи, локальні моделі, агенти, інтеграції, human-AI interaction.','work.software':'Вебсистеми, автоматизація, системна інтеграція, інфраструктурні рішення.','work.research':'Дослідження, open data, аналітика, візуалізація складних даних.','work.creative':'Експериментальні цифрові продукти на стику дизайну, програмування, AI та медіа.',
'projects.subtitle':'Проєкти','projects.all':'Усі проєкти','projects.jwr':'Незалежна open-data дослідницька платформа','projects.local':'Локальна AI-помічниця','projects.budget':'Особистий локальний бюджет','projects.tax':'Калькулятор податків для України',
'cases.safe':'без чутливих деталей','cases.minerTitle':'Система раннього детекту майнерів','cases.miner':'Моніторинг системи на ознаки майнерів та унеможливлення їх дії.','cases.securityTitle':'Багатошаровий захист IT-інфраструктури','cases.security':'Комплексна система захисту ресурсів компанії в умовах підвищеної секретності.','cases.docsTitle':'Технічна документація великого IT-проєкту','cases.docs':'Розробка документації в умовах мінімальної співпраці з персоналом.','cases.methodTitle':'Методичні матеріали для програмного продукту','cases.method':'Структуровані навчальні та методичні матеріали.','cases.learningTitle':'Локальна ШІ-система для автонавчання','cases.learning':'Впровадження локальної AI-системи у внутрішні бізнес-процеси.',
'about.p1':'Robot Aoi no Kokoro — студія AI, досліджень і цифрової інженерії, де людський контекст стоїть у центрі.','about.p2':'Робимо локальні AI-системи, open-data платформи та цифрові продукти з фокусом на людину, приватність і довгострокову цінність.','about.more':'Дізнатися більше',
'principles.humanTitle':'Людина в центрі','principles.human':'Людина — центр кожного рішення.','principles.evidenceTitle':'Прозорість і довіра','principles.evidence':'Прозорість у даних, алгоритмах і діях.','principles.privacyTitle':'Приватність','principles.privacy':'Приватність і безпека — наш пріоритет.','principles.kaizenTitle':'Kaizen 改善','principles.kaizen':'Ми навчаємось, експериментуємо і стаємо кращими.','contact.lead':'Створімо майбутнє разом.'},
en:{
'nav.home':'Home','nav.about':'About','nav.projects':'Projects','nav.work':'What we do','nav.principles':'Principles','nav.contact':'Contact',
'hero.translation':'A place that connects hearts.','hero.summary':'We create technology, research and digital products where human needs meet artificial intelligence.','hero.projects':'Our projects','hero.about':'About the studio',
'manifest.translation':'From robot to human. From human to robot.','manifest.p1':'We believe technology should strengthen people where it is needed, while leaving room for empathy, creativity and deep understanding.','manifest.p2':'We build systems that help people understand a complex world, make decisions, create and interact with digital systems more naturally.','manifest.p3':'Technology is not the goal. It is a bridge between people, and that is where its real value begins.',
'work.subtitle':'What we build','work.lead':'Our solutions emerge where technology, research, creativity and human needs intersect.','work.all':'All projects','work.ai':'AI systems, local models, agents, integrations and human-AI interaction.','work.software':'Web systems, automation, systems integration and infrastructure solutions.','work.research':'Research, open data, analytics and visualization of complex data.','work.creative':'Experimental digital products at the intersection of design, software, AI and media.',
'projects.subtitle':'Projects','projects.all':'All projects','projects.jwr':'Independent open-data research platform','projects.local':'Local AI assistant','projects.budget':'Personal local budgeting system','projects.tax':'Tax calculator for Ukraine',
'cases.safe':'without sensitive details','cases.minerTitle':'Early miner detection system','cases.miner':'Monitoring for miner-related indicators and preventing malicious activity.','cases.securityTitle':'Layered IT infrastructure protection','cases.security':'Comprehensive protection of company resources in high-secrecy environments.','cases.docsTitle':'Technical documentation for a large IT project','cases.docs':'Documentation development with minimal staff cooperation.','cases.methodTitle':'Methodical materials for a software product','cases.method':'Structured training and methodological materials.','cases.learningTitle':'Local AI self-learning system','cases.learning':'Deployment of a local AI system into internal business processes.',
'about.p1':'Robot Aoi no Kokoro is an AI, research and digital engineering studio with human context at its center.','about.p2':'We build local AI systems, open-data platforms and digital products focused on people, privacy and long-term value.','about.more':'Learn more',
'principles.humanTitle':'Human first','principles.human':'People are at the center of every decision.','principles.evidenceTitle':'Transparency and trust','principles.evidence':'Transparency in data, algorithms and actions.','principles.privacyTitle':'Privacy','principles.privacy':'Privacy and security are our priority.','principles.kaizenTitle':'Kaizen 改善','principles.kaizen':'We learn, experiment and keep improving.','contact.lead':'Let’s build the future together.'},
ja:{
'nav.home':'ホーム','nav.about':'スタジオについて','nav.projects':'プロジェクト','nav.work':'活動領域','nav.principles':'理念','nav.contact':'お問い合わせ',
'hero.translation':'心と心をつなぐ場所。','hero.summary':'私たちは、人のニーズと人工知能が出会う場所で、技術・研究・デジタルプロダクトをつくります。','hero.projects':'私たちのプロジェクト','hero.about':'スタジオについて',
'manifest.translation':'ロボットから人へ。人からロボットへ。','manifest.p1':'私たちは、技術は必要なところで人を支え、共感・創造性・深い理解のための余白を残すべきだと考えています。','manifest.p2':'複雑な世界を理解し、判断し、創造し、デジタルシステムとより自然に関われるような仕組みをつくります。','manifest.p3':'技術そのものが目的ではありません。人と人をつなぐ橋であることに、本当の価値があります。',
'work.subtitle':'私たちがつくるもの','work.lead':'私たちのプロダクトは、技術・研究・創造性・人のニーズが交わるところから生まれます。','work.all':'すべてのプロジェクト','work.ai':'AIシステム、ローカルモデル、エージェント、統合、Human-AI interaction。','work.software':'Webシステム、自動化、システム統合、インフラソリューション。','work.research':'研究、オープンデータ、分析、複雑なデータの可視化。','work.creative':'デザイン、ソフトウェア、AI、メディアが交わる実験的なデジタルプロダクト。',
'projects.subtitle':'プロジェクト','projects.all':'すべてのプロジェクト','projects.jwr':'独立系オープンデータ研究プラットフォーム','projects.local':'ローカルAIアシスタント','projects.budget':'ローカル家計管理システム','projects.tax':'ウクライナ向け税計算ツール',
'cases.safe':'機密情報を除いた概要','cases.minerTitle':'マイナー早期検知システム','cases.miner':'隠れたマイニングの兆候を監視し、その動作を防止します。','cases.securityTitle':'多層ITインフラ保護','cases.security':'高い機密性が必要な環境向けの包括的な保護。','cases.docsTitle':'大規模ITプロジェクトの技術文書','cases.docs':'スタッフとの協力が限られる状況での技術文書作成。','cases.methodTitle':'ソフトウェア製品向け教材','cases.method':'体系化された学習・方法論資料。','cases.learningTitle':'ローカルAI自己学習システム','cases.learning':'社内業務プロセスへローカルAIを導入します。',
'about.p1':'Robot Aoi no Kokoro は、人を中心に据えたAI・研究・デジタルエンジニアリングのスタジオです。','about.p2':'人、プライバシー、長期的な価値を重視し、ローカルAI、オープンデータ、デジタルプロダクトをつくります。','about.more':'詳しく見る',
'principles.humanTitle':'人を中心に','principles.human':'すべての判断の中心に人を置きます。','principles.evidenceTitle':'透明性と信頼','principles.evidence':'データ、アルゴリズム、行動の透明性を大切にします。','principles.privacyTitle':'プライバシー','principles.privacy':'プライバシーと安全性を最優先します。','principles.kaizenTitle':'Kaizen 改善','principles.kaizen':'学び、試し、少しずつ良くしていきます。','contact.lead':'一緒に未来をつくりましょう。'}
};
const modalInfo={
uk:{local:'Локальна AI-помічниця з пам’яттю, модулями, WebUI та голосовими експериментами.',budget:'Локальна система сімейного бюджету без передачі приватних даних зовнішнім сервісам.',miner:'Раннє виявлення ознак прихованого майнінгу та блокування його дії.',security:'Багатошаровий захист інфраструктури для середовищ із підвищеною секретністю.',docs:'Відновлення структури системи та підготовка технічної документації за обмеженої співпраці.',method:'Структуровані методичні та навчальні матеріали для складного програмного продукту.',learning:'Локальна AI-система для накопичення знань, навчання та інтеграції у бізнес-процеси.'},
en:{local:'A local AI assistant with memory, modules, WebUI and voice experiments.',budget:'A local family budgeting system that keeps private data off external services.',miner:'Early detection of hidden mining activity and mechanisms to stop it.',security:'Layered infrastructure protection for high-secrecy environments.',docs:'Reconstruction of system structure and technical documentation with limited staff cooperation.',method:'Structured methodological and training materials for complex software products.',learning:'A local AI system for knowledge accumulation, learning and business-process integration.'},
ja:{local:'記憶、モジュール、WebUI、音声実験を備えたローカルAIアシスタント。',budget:'個人データを外部サービスに送らないローカル家計管理システム。',miner:'隠れたマイニングを早期検知し動作を止める仕組み。',security:'高機密環境向けの多層インフラ保護。',docs:'限られた協力環境でのシステム構造復元と技術文書作成。',method:'複雑なソフトウェア向けの体系的な教材と方法論資料。',learning:'知識蓄積、学習、業務統合のためのローカルAIシステム。'}};
function setLang(l){lang=l;localStorage.setItem('aoi-lang',l);document.documentElement.lang=l;code.textContent=l==='ja'?'JP':l.toUpperCase();document.querySelectorAll('[data-i18n]').forEach(el=>{const v=dict[l][el.dataset.i18n];if(v!==undefined){if(v.includes('<br>'))el.innerHTML=v;else el.textContent=v}});m.hidden=true;t.setAttribute('aria-expanded','false')}
if(t)t.addEventListener('click',()=>{m.hidden=!m.hidden;t.setAttribute('aria-expanded',String(!m.hidden))});
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
document.querySelectorAll('[data-mobile-lang]').forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.mobileLang)));
if(menu)menu.addEventListener('click',()=>{panel.hidden=!panel.hidden;menu.setAttribute('aria-expanded',String(!panel.hidden))});
if(panel)panel.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>panel.hidden=true));
function openModal(title,key){if(!modal)return;mt.textContent=title;mp.textContent=(modalInfo[lang]&&modalInfo[lang][key])||key||'';modal.showModal()}
document.querySelectorAll('[data-modal-title]').forEach(b=>b.addEventListener('click',()=>openModal(b.dataset.modalTitle,b.dataset.modalText)));
document.querySelectorAll('[data-case]').forEach(b=>b.addEventListener('click',()=>openModal(b.querySelector('h3').textContent,b.dataset.case)));
const close=document.querySelector('.modal-close');if(close)close.addEventListener('click',()=>modal.close());if(modal)modal.addEventListener('click',e=>{if(e.target===modal)modal.close()});
const year=document.getElementById('year');if(year)year.textContent=new Date().getFullYear();setLang(lang);
if('serviceWorker'in navigator)addEventListener('load',()=>navigator.serviceWorker.register('/sw.js?v=7').catch(()=>{}));
})();
